### ISSUE TITLE
Upute za pokretanje aplikacije

### ISSUE THREAD

**Issue by sbuljat** [MarkoMiletic1996/pzw_zavrsniProjekt#1]
Potrebno je u README napisati upute za pokretanje aplikacije

**Comment by MarkoMiletic1996** [comment]
Napravio samU PyCharmu sam radio, je li to kakav problem?
LP

Sent from Yahoo Mail on Android 
 
  On čet, velj 27, 2020 at 19:53, Stjepan Buljat<notifications@github.com> wrote:   
Potrebno je u README napisati upute za pokretanje aplikacije

**Comment by sbuljat** [comment]
Nije to problem, ali napiši kako se podiže flask iz komandne linije - ono što smo standardno na svakom predavanju imali.

**Comment by MarkoMiletic1996** [comment]
Postavio sam.
LP

Sent from Yahoo Mail on Android 
 
  On pet, velj 28, 2020 at 8:04, Stjepan Buljat<notifications@github.com> wrote:   
Nije to problem, ali napiši kako se podiže flask iz komandne linije - ono što smo standardno na svakom predavanju imali.
